moesifmiddleware.go
Add: Transaction Id to Request-Response Headers
=> Add: Transaction Id to Request-Response Headers

README.md, moesifmiddleware.go
Add: Configuration Options
Refactor: Event Request Model
=> Add: Configuration Options

Gopkg.lock, Gopkg.toml, moesifmiddleware.go
Fix: ShouldSkip function params type
Update: moesifapi dependency
=> Fix: ShouldSkip function params type

README.md, captureoutgoing.go, moesifmiddleware.go, sendmoesif.go
=> Add: Capture Outgoing Request

captureoutgoing.go, moesifmiddleware.go, sendmoesif.go
Add: Encode non JSON to Base64 and use the "base64" transfer_encoding
=> Add: Encode non JSON to Base64 and use the "base64" transfer_encoding

captureoutgoing.go, clientip.go, sendmoesif.go
Add: Support for proxy server where we could not get the ip address
=> Add: Get Client Ip Address

README.md, clientip.go
=> Update: README.md

moesifmiddleware.go
Add: Function to start capture outgoing requests
=> Add: Function to start capture outgoing requests

moesifmiddleware.go
Refactor: Remove check to start capture outgoing request
=> Refactor: Remove check to start capture outgoing request

README.md, moesifmiddleware.go
Add: Update user and batch users functions
Add: Update user and batch companies functions
=> Add: Update user and batch users functions

README.md, captureoutgoing.go, moesifmiddleware.go, sendmoesif.go
Add: IdentifyCompany and IdentifyCompanyOutgoing configuration option
=> Add: IdentifyCompany and IdentifyCompanyOutgoing configuration option

README.md, captureoutgoing.go, moesifmiddleware.go
Add: LogBody configuration option to remove request and response body
=> Add: LogBody configuration option to remove request and response body

Gopkg.lock, Gopkg.toml, README.md, captureoutgoing.go, go.mod, go.sum, moesifmiddleware.go, sendmoesif.go
Add: Direction and weight field to event model
Refactor: Update moesifapi-go dependency to 1.0.3
Refactor: Update REAMDE.md
=> Add: Direction and weight field to event model

README.md
Refactor: Update README.md users and companies section
=> Refactor: Update README.md users and companies section

Gopkg.lock, Gopkg.toml, go.mod, go.sum, moesifmiddleware.go
Refactor: Remove capture_outgoing_request configuration option
=> Refactor: Remove capture_outgoing_request configuration option

Gopkg.lock, Gopkg.toml, README.md, go.mod, go.sum
Refactor: Bump moesifapi-go dependency to 1.0.4
=> Refactor: Bump moesifapi-go dependency to 1.0.4

Gopkg.lock, Gopkg.toml, README.md, appconfig.go, captureoutgoing.go, clientip.go, go.mod, go.sum, loggerhelper.go, moesifmiddleware.go, sendmoesif.go
Add: Support for sampling events
Add: Support for masking headers and body
Add: Helper functions to parse Body
Refactor: Update README.md
=> Add: Support for sampling events

Gopkg.lock, README.md, go.mod, go.sum, moesifmiddleware.go
Add: Support for batch config options
Refactor: Update README.md
=> Add: Support for batch config options

moesifmiddleware.go
Use ioutil for compatibility with Go 1.12+
=> Use ioutil for compatibility with Go 1.12+

appconfig.go, appconfig_test.go, governance_rules.go, moesifmiddleware.go, sendmoesif.go
https://www.pivotaltracker.com/story/show/182265240
=> Governance Rule Support

appconfig.go, go.mod, governance_rules.go, moesifmiddleware.go, sendmoesif.go
Add support for parsing GraphQL request contents and applying governance rules to requests
Includes quicker config and governance rule updates
=> GraphQL support and fixes

README.md, sendmoesif.go
Refactor: Print skipped event log only if debug flag is set
Refactor: Update README.md
=> Refactor: Print skipped event log only if debug flag is set
